artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/venura-Pussella/Nadu_2_Price_Prediction/blob/main/Lstm_Dates.xlsx
  local_data_file: artifacts/data_ingestion/Lstm_Dates.xlsx
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Lstm_Dates.xlsx
  STATUS_FILE: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  unzip_data_dir: artifacts/data_ingestion/Lstm_Dates.xlsx
  local_data_file: artifacts/data_preprocessing/Lstm_data_preprocessed.xlsx

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preprocessing/Lstm_data_preprocessed.xlsx
  lambda_value: artifacts/data_transformation/lambda_value.txt
  local_data_file: artifacts/data_transformation/lstm_transformed.xlsx
  min_max_scaler_file: artifacts/data_transformation/min_max_scaler.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  root_dir_train: artifacts/model_trainer/train
  root_dir_test: artifacts/model_trainer/test
  local_data_path: artifacts/data_transformation/lstm_transformed.xlsx
  train_x_data_file: artifacts/model_trainer/train/train_x.xlsx
  train_y_data_file: artifacts/model_trainer/train/train_y.xlsx
  train_dates_data_file: artifacts/model_trainer/train/train_dates.xlsx
  test_dates_data_file: artifacts/model_trainer/test/test_dates.xlsx
  test_x_data_file: artifacts/model_trainer/test/test_x.xlsx
  test_y_data_file: artifacts/model_trainer/test/test_y.xlsx
  model_checkpoint_path: artifacts/model_trainer/model/5day_model.keras
  filters: 64
  kernel_size: 3
  activation1: 'relu'
  sequence_length: 30
  forecast_horizon: 5
  n_units_layer1: 128
  n_units_layer2: 64
  n_units_layer3: 32
  n_units_layer4: 5
  activation2: 'linear'
  dropout_rate: 0.2
  optimizer: 'adam'
  loss_function: 'mean_squared_error'
  epochs: 100
  batch_size: 64
  validation_split: 0.2

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer/model/5day_model.keras
  metric_file_name: artifacts/model_evaluation/metrics.xlsx